spring:
  datasource:
    generate-unique-name: false

    url: jdbc:h2:./devdb
    username: sa
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update